version: 0.1
globalTimeout: 150
testSuiteTimeout: 150
testSuiteStep: 150

runson: ${matrix.os}
retryOnFailure: false

autosplit: true

maxRetries: 1
parallelism: 2
concurrency: 3

matrix:
  os: [mac, win, linux]

cacheKey: '{{ checksum "package.json" }}'
cacheDirectories:
  - node_modules

testDiscovery:
  type: raw
  mode: remote
  command: grep -lr 'describe' specs/*.spec.js

pre:
  - node scripts/clear-chrome-lock.js
  - npm install

post:
  - cat yaml/.hyperexecute_hybrid.yaml

testRunnerCommand: npm test $test

jobLabel: [puppeteer-Mocha, hybrid]